### ISSUE TITLE
missing `typing-extensions` dependency

### ISSUE THREAD

**Issue by xylar** [conda-forge/numcodecs-feedstock#87]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/gdal-feedstock/pull/637, we are seeing:

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/test_tmp/run_test.py", line 3, in <module>
    import zarr
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/zarr/__init__.py", line 2, in <module>
    from zarr.codecs import *
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/zarr/codecs.py", line 2, in <module>
    from numcodecs import *
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/numcodecs/__init__.py", line 26, in <module>
    from numcodecs.zlib import Zlib
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/numcodecs/zlib.py", line 5, in <module>
    from .compat import ndarray_copy, ensure_contiguous_ndarray
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/numcodecs/compat.py", line 10, in <module>
    from .ndarray_like import NDArrayLike, is_ndarray_like
  File "/home/conda/feedstock_root/build_artifacts/gdal-split_1656705056514/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/numcodecs/ndarray_like.py", line 7, in <module>
    from typing_extensions import Protocol, runtime_checkable
ModuleNotFoundError: No module named 'typing_extensions'
```

### Installed packages

```shell
CI (not available)
```

### Environment info

```shell
CI (not available)
```

**Comment by xylar** [comment]
This seems to have been added about 4 months ago, see:
https://github.com/zarr-developers/numcodecs/blame/v0.10.0/setup.py#L341

**Comment by ap--** [comment]
I ran into this with https://github.com/conda-forge/tiffslide-feedstock

`numcodecs` only needs [typing-extensions during runtime for py<38](https://github.com/zarr-developers/numcodecs/blob/main/numcodecs/ndarray_like.py#L4) but its setup.py depends on typing-extensions [without restricting the python version](https://github.com/zarr-developers/numcodecs/blob/0b4cf1189b8b5b7f9c779eff63efcdec8bd38155/setup.py#L341).

This can cause `pip check` to fail in the conda-forge ci:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=529644&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=415
